### ISSUE TITLE
能否简单说明和列举一下工程使用到的技术？

### ISSUE THREAD

**Issue by giticaniup** [baloonwj/flamingo#2]
C++ 初学者，希望了解一下这个工程中所使用到的相关技术，例如：PC端的UI是基于什么做的？
感谢。

**Comment by edidada** [comment]
我也是初学者，跟你交流下吧，我觉得你可以找到main函数，一行一行的去看。我目前了解到的UI方式有 QT WPF WTL等等，用C#的排除
